### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by claytoncohn** [EddieWen-Taiwan/typewriting#2]
Would there be any way to have the characters make a typing sound as they appeared on the screen? I tried to figure it out for the last few hours but haven't been able to. Thanks!

**Comment by eddiewentw** [comment]
Hi, I think it's workable. But I‘m on vacation right now LOL. Maybe I will try this next week or after I finish the vacation(28th).
I googled and got [this](http://stackoverflow.com/questions/879152/how-do-i-make-javascript-beep). If you wanna do this before me, you could insert the code at [Line34](https://github.com/EddieWen-Taiwan/TypeWriting.js/blob/master/src/typewriting.js#L34) in the file - /src/typewriting.js
